/* Auto-generated by tools/gen_pinconfigs.py from AppleALC PinConfigs.kext */
/* Do not edit manually. */

#ifndef _APPLEALC_PIN_CONFIGS_H
#define _APPLEALC_PIN_CONFIGS_H

#include <libkern/OSTypes.h>

typedef struct {
    UInt8  nid;
    UInt32 pinConfig;
} __attribute__((packed)) ALCPinConfig;

typedef struct {
    UInt32 codecId;
    UInt32 layoutId;
    UInt16 pinConfigStart;
    UInt8  pinConfigCount;
    UInt16 extraVerbStart;
    UInt16 extraVerbCount;
    UInt16 wakeVerbStart;
    UInt16 wakeVerbCount;
} __attribute__((packed)) ALCConfigEntry;

#define ALC_PIN_CONFIGS_COUNT  4173
#define ALC_EXTRA_VERBS_COUNT  1601
#define ALC_WAKE_VERBS_COUNT   1089
#define ALC_CONFIG_ENTRIES_COUNT 655

extern const ALCPinConfig   gALCPinConfigs[];
extern const UInt32         gALCExtraVerbs[];
extern const UInt32         gALCWakeVerbs[];
extern const ALCConfigEntry gALCConfigEntries[];

const ALCConfigEntry* alcLookupPinConfig(UInt32 codecId, UInt32 layoutId);

#endif /* _APPLEALC_PIN_CONFIGS_H */
